language: python
rvm:
python:
-3.7
install:
    - pip install tox-travis
    - pip install -r requirements.txt
script:
 - python manage.py test
 - tox
 - pytest
 - black 
 - flake8
after_script:
- coveralls